# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# The secret key is shared between your server and the WebLayoutEditor server.
# It is used to encrypt the authentication token passed between the two servers.


development:
  secret_key_base: 1247ad0470fa46427fdff6010c1abcc53f3c81f37c324d421adcae8c42d5e17d37574edfa06e8d30fc58973974b2d26caf44d4b22815f49d1dd154db74be49ac
  awl_shared_secret: CA8BC51AD641ADFAC55124FB3E000000

test:
  secret_key_base: 3173e32616b9c88cfbc8eea128a089c50e781409d9a5acfee7cb6b7f9bc2daffb28ff59bd28deca34932278f6accbbf74466b0d520f049533ba43d33dff75be8
  awl_shared_secret: CA8BC51AD641ADFAC55124FB3E000000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  awl_shared_secret: <% ENV["AWL_SHARED_SECRET"] %>
